version: '3.4'
  
services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
      - "5341:5341"

  identity-db:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - microshop-identity-sqldata:/var/opt/mssql

  catalog-db:
    ports:
      - 27017:27017
    volumes:
      - microshop-catalog-mongodata:/data/db

  cart-db:
    ports:
      - 6379:6379

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672


  microshop-view:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:81;http://+:80
      - Urls__Identity=${MICROSHOP_EXTERNAL_DNS_NAME_OR_IP}:8002/
      - Urls__Apigateway=${MICROSHOP_EXTERNAL_DNS_NAME_OR_IP}:8001/
    ports:
      - 7000:80
      - 8000:81
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - apigateway
      - rabbitmq
      - seq

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:81;http://+:80
      - Urls__Identity=${MICROSHOP_EXTERNAL_DNS_NAME_OR_IP}:8002/
    ports:
      - 7001:80
      - 8001:81
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - identity-api
      - catalog-api
      - orders-api
      - cart-api
      - seq
      - rabbitmq

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:81;http://+:80
      - Urls__View=${MICROSHOP_EXTERNAL_DNS_NAME_OR_IP}:8000/
      - Urls__Identity=${MICROSHOP_EXTERNAL_DNS_NAME_OR_IP}:8002/
    ports:
      - 7002:80
      - 8002:81
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - identity-db
      - rabbitmq
      - seq

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__HTTPs__Url=https://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Url=https://0.0.0.0:82
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - Urls__Identity=${MICROSHOP_EXTERNAL_DNS_NAME_OR_IP}:8002/
    ports:
      - 7003:80
      - 8003:81
      - 9003:82
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - catalog-db
      - rabbitmq
      - seq

  cart-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__HTTPs__Url=https://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Url=https://0.0.0.0:82
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - Urls__Identity=${MICROSHOP_EXTERNAL_DNS_NAME_OR_IP}:8002/
    ports:
      - 7004:80
      - 8004:81
      - 9004:82
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - cart-db
      - rabbitmq
      - seq

  orders-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:81;http://+:80
      - Urls__Identity=${MICROSHOP_EXTERNAL_DNS_NAME_OR_IP}:8002/
    ports:
      - 7005:80
      - 8005:81
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - rabbitmq
      - seq
      
  microshop-healthchecksui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:81;http://+:80
    ports:
      - 7010:80
      - 8010:81
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - apigateway
      - identity-api
      - catalog-api
      - orders-api
      - cart-api
      - seq
      - rabbitmq

volumes:
  microshop-identity-sqldata:
    external: false
  microshop-catalog-mongodata:
    external: false

