name: Build Admin

on:
  push:
    branches: [ "main" ]
    paths:
    - Src/BuildingBlocks/**
    - Src/View/MicroShop.Admin/**
    - .github/workflows/build-admin.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Src/View/MicroShop.Admin/Dockerfile --tag microshop/microshop-admin