name: Build ApiGateway

on:
  push:
    branches: [ "main" ]
    paths:
    - Src/BuildingBlocks/**
    - Src/ApiGateways/ApiGateway/**
    - .github/workflows/build-apigateway.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Src/ApiGateways/ApiGateway/Dockerfile --tag microshop/apigateway