name: Build Payments Api

on:
  push:
    branches: [ "main" ]
    paths:
    - Src/BuildingBlocks/**
    - Src/Services/Payments/**
    - .github/workflows/build-payments.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Src/Services/Payments/Payments.Api/Dockerfile --tag microshop/payments-api